//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pavilions
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PavilionEntities : DbContext
    {
        public PavilionEntities()
            : base("name=PavilionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cities_> Cities_ { get; set; }
        public virtual DbSet<Employees_> Employees_ { get; set; }
        public virtual DbSet<Malls_> Malls_ { get; set; }
        public virtual DbSet<MallStatuses_> MallStatuses_ { get; set; }
        public virtual DbSet<Pavilions_> Pavilions_ { get; set; }
        public virtual DbSet<PavilionsLease_> PavilionsLease_ { get; set; }
        public virtual DbSet<PavilionStatuses_> PavilionStatuses_ { get; set; }
        public virtual DbSet<Roles_> Roles_ { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tenants_> Tenants_ { get; set; }
        public virtual DbSet<MallsList> MallsList { get; set; }

        private static PavilionEntities _context;

        public static PavilionEntities GetContext()
        {
            if (_context == null)
                _context = new PavilionEntities();
            return _context;

        }
    }
}
