//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pavilions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pavilions_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pavilions_()
        {
            this.PavilionsLease_ = new HashSet<PavilionsLease_>();
        }
    
        public int PavilionId { get; set; }
        public string PavilionNumber { get; set; }
        public Nullable<int> MallId { get; set; }
        public Nullable<int> LevelNumber { get; set; }
        public Nullable<int> PavilionStatusId { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<double> SquareMeterCost { get; set; }
        public Nullable<double> ValueAddedFactor { get; set; }
    
        public virtual Malls_ Malls_ { get; set; }
        public virtual PavilionStatuses_ PavilionStatuses_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PavilionsLease_> PavilionsLease_ { get; set; }
    }
}
